Bump more references of dandiset to dataset
lincbrain/linc-archive pull request #30
Opened 2024-01-17 21:32 UTC by aaronkanzer

2024-01-17 22:33 UTC, kabilar commented on dandiapi/api/templates/api/account/base.html
> +  <title>LINC Archive</title>
```suggestion
  <title>LINC Platform</title>
```

2024-01-17 22:33 UTC, kabilar commented on web/src/components/DandiFooter.vue
> +          &copy; 2024 The LINC Archive Team<br>
```suggestion
          &copy; 2023 - 2024 LINC Team<br>
```

2024-01-17 22:34 UTC, kabilar requested changes
Thank you @aaronkanzer.  A few minor comments above.

2024-01-31 22:30 UTC, aaronkanzer commented on web/src/components/DandiFooter.vue
> +          &copy; 2024 The LINC Archive Team<br>
Updated!

2024-01-31 22:30 UTC, aaronkanzer commented on dandiapi/api/templates/api/account/base.html
> +  <title>LINC Archive</title>
Updated!

2024-01-31 22:51 UTC, kabilar approved these changes

2024-01-31 22:52 UTC, merged